version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache2
    ports:
      - 8080:80
    restart: always
    tty: true
    stdin_open: true
    networks:
      - web-db-net

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ports:
      - 9201:9200

  mysqld:
    image: mysql:5.7
    restart: always
    container_name: mysqld
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: magento234
      MYSQL_ROOT_PASSWORD: rootroot   
    networks:
      - web-db-net 

networks:
    web-db-net:       